//@ui5-bundle costescenter/Component-preload.js
sap.ui.predefine("costescenter/Component", ["sap/ui/core/UIComponent","costescenter/model/models"],(e,t)=>{"use strict";return e.extend("costescenter.Component",{metadata:{manifest:"json",interfaces:["sap.ui.core.IAsyncContentCreation"]},init(){e.prototype.init.apply(this,arguments);this.setModel(t.createDeviceModel(),"device");this.getRouter().initialize()}})});
sap.ui.predefine("costescenter/controller/App.controller", ["sap/ui/core/mvc/Controller"],e=>{"use strict";return e.extend("costescenter.controller.App",{onInit(){}})});
sap.ui.predefine("costescenter/controller/CostCenter.controller", ["sap/ui/core/mvc/Controller","sap/ui/model/json/JSONModel"],function(e,n){"use strict";return e.extend("costescenter.controller.CostCenter",{onInit:function(){var e={nodes:[{name:"DATO 1",budget:"1000000",nodes:[{name:"DATO 2",budget:"300000",nodes:[{name:"Mini dato",budget:"100000"},{name:"Mini dato 2",budget:"200000"}]},{name:"DATO 3",budget:"700000",nodes:[{name:"Infrastructure",budget:"400000"},{name:"Development",budget:"300000"}]}]}]};var t=new n(e);this.getView().setModel(t);this.byId("treeTable").bindRows({path:"/nodes",parameters:{arrayNames:["nodes"]}})}})});
sap.ui.predefine("costescenter/model/models", ["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
sap.ui.require.preload({
	"costescenter/i18n/i18n.properties":'# This is the resource bundle for costescenter\n\n#Texts for manifest.json\n\n#XTIT: Application name\nappTitle=App Title\n\n#YDES: Application description\nappDescription=An SAP Fiori application.\n#XTIT: Main view title\ntitle=App Title',
	"costescenter/manifest.json":'{"_version":"1.85.0","sap.app":{"id":"costescenter","type":"application","i18n":{"bundleUrl":"i18n/i18n.properties","supportedLocales":[""]},"applicationVersion":{"version":"0.0.1"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","sourceTemplate":{"id":"@sap/generator-fiori:basic","version":"1.25.0","toolsId":"42b5f3d5-9fff-424b-b6fa-691f49e35f26"}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":false,"dependencies":{"minUI5Version":"1.148.1","libs":{"sap.m":{},"sap.ui.core":{},"sap.ui.table":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"costescenter.i18n.i18n","supportedLocales":[""]}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","controlAggregation":"pages","controlId":"app","transition":"slide","type":"View","viewType":"XML","path":"costescenter.view","async":true,"viewPath":"costescenter.view"},"routes":[{"name":"RouteCostCenter","pattern":":?query:","target":["TargetCostCenter"]}],"targets":{"TargetCostCenter":{"id":"CostCenter","name":"CostCenter"}}},"rootView":{"viewName":"costescenter.view.App","type":"XML","id":"App","async":true},"flexBundle":false}}',
	"costescenter/view/App.view.xml":'<mvc:View controllerName="costescenter.controller.App"\n    displayBlock="true"\n    xmlns:mvc="sap.ui.core.mvc"\n    xmlns="sap.m"><App id="app"></App></mvc:View>',
	"costescenter/view/CostCenter.view.xml":'<mvc:View\n    controllerName="costescenter.controller.CostCenter"\n    xmlns:mvc="sap.ui.core.mvc"\n    xmlns="sap.m"\n    xmlns:t="sap.ui.table"><Page title="Cost Center Hierarchy"><content><t:TreeTable\n                id="treeTable"\n                selectionMode="None"\n                visibleRowCount="10"><t:columns><t:Column width="300px"><Label text="Cost Center"/><t:template><Text text="{name}"/></t:template></t:Column><t:Column width="150px"><Label text="Budget"/><t:template><Text text="{budget}"/></t:template></t:Column></t:columns></t:TreeTable></content></Page></mvc:View>'
});
//# sourceMappingURL=Component-preload.js.map
